version: '3.1'
services:
    api:
        build:
            context: ./compose
            dockerfile: ./Dockerfile
        volumes:
            - ./app:/app
            - ./tests:/tests
        ports:
            - 8000:8000/tcp
        tty: true
        command: ["./start"]
