# Generated by Django 2.1.2 on 2018-10-03 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Length must be 4', regex='^.{4}$')])),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_repayed', models.BooleanField(default=False)),
            ],
        ),
    ]
